@EmployeeWebAPI_HostAddress = http://localhost:5000

###########################################################
### Generate JWT Token
###########################################################

GET {{EmployeeWebAPI_HostAddress}}/api/Auth
Accept: application/json

###

###########################################################
### Get All Employees (Requires JWT Token)
###########################################################

GET {{EmployeeWebAPI_HostAddress}}/api/Employee
Accept: application/json
Authorization: Bearer YOUR_JWT_TOKEN

###

###########################################################
### Get Employee By Id
###########################################################

GET {{EmployeeWebAPI_HostAddress}}/api/Employee/1
Accept: application/json
Authorization: Bearer YOUR_JWT_TOKEN

###

###########################################################
### Create Employee
###########################################################

POST {{EmployeeWebAPI_HostAddress}}/api/Employee
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

{
  "id": 3,
  "name": "Rohit",
  "salary": 55000,
  "permanent": true,
  "department": {
    "id": 3,
    "name": "Finance"
  },
  "skills": [
    {
      "id": 5,
      "name": "Accounting"
    }
  ],
  "dateOfBirth": "2000-08-20T00:00:00"
}

###

###########################################################
### Update Employee
###########################################################

PUT {{EmployeeWebAPI_HostAddress}}/api/Employee/1
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

{
  "id": 1,
  "name": "Arif Updated",
  "salary": 70000,
  "permanent": true,
  "department": {
    "id": 1,
    "name": "IT"
  },
  "skills": [
    {
      "id": 1,
      "name": "ASP.NET Core"
    }
  ],
  "dateOfBirth": "2002-05-10T00:00:00"
}

###

###########################################################
### Delete Employee
###########################################################

DELETE {{EmployeeWebAPI_HostAddress}}/api/Employee/1
Authorization: Bearer YOUR_JWT_TOKEN

###

###########################################################
### Invalid Request (No Token)
###########################################################

GET {{EmployeeWebAPI_HostAddress}}/api/Employee
Accept: application/json

###

###########################################################
### Invalid Token
###########################################################

GET {{EmployeeWebAPI_HostAddress}}/api/Employee
Accept: application/json
Authorization: Bearer INVALID_TOKEN

###